version: '3'

services:
  fer-app:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - .:/app
      - model-data:/app/checkpoints
    environment:
      - PYTHONUNBUFFERED=1
    # Add the privileged flag for device access (Helps with webcam on some systems)
    privileged: true
    # Uncomment the appropriate device mapping for your OS:
    
    # For Linux: Map the video device directly
    # devices:
    #   - "/dev/video0:/dev/video0"
    
    # For macOS: Use device passthrough (requires additional setup)
    # See webcam-setup.md for macOS-specific instructions
    security_opt:
      - seccomp:unconfined
    devices:
      - "/dev/video0:/dev/video0"
    restart: unless-stopped

volumes:
  model-data:
    driver: local
